### ISSUE TITLE
Switching from os.system to subprocess

### ISSUE THREAD

**Issue by batukav** [NMRLipids/Databank#14]
This is a rather low priority issue but I'd like to bring using subprocess instead of os.system to the attention. At the moment we are handling the interactions with the system through the os.system module (creating directories, copying files etc.). Generally it is recommended to use subprocess module instead of the os.system as it provides more flexibility. 

It might be a good idea at the moment to decide on which of these modules to use. This also applies to the all analysis scripts we are planning to deploy with the databank.

I am not fully informed with the advantages of the subprocess module however someone from the community with more information might want chime in.

**Comment by ohsOllila** [comment]
Is this still relevant?

**Comment by batukav** [comment]
No, this is not relevant anymore. I'm closing this issue.
