### ISSUE TITLE
Predicting multicomponent membrane properties from the NMRlipids databank (data from different membrane compositions needed)

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/Databank#142]
Inspired by the reviewer's comments, I made a simple code that predicts multi-component membrane properties (now area per lipid, but could be extended to any property) using linear regression model based on the data in the NMRlipids databank. The code is available from here: https://github.com/NMRLipids/DataBankManuscript/blob/main/scripts/predictor.ipynb (note that it currently needs the development branch of NMRlipids databank due to the reorganization of API). 

To potentially include such results into the NMRlipids databank manuscript, we should 1) test how well this works and 2) demonstrate some practical application(s). 

For 1), my current idea is to predict properties of typical biological membrane mixtures, and then test the predictions by running simulations with these membrane compositions. The membrane compositions could be taken, for example, from different organelles in cells available at least in these publications: http://dx.doi.org/10.3390/ijms20092167 and https://doi.org/10.1038/nrm2330, or bacteria (https://doi.org/10.1016/j.celrep.2020.108165). 

For 2), we could then predict how membrane properties change when lipid composition is changing with different diseases. This is discussed in the literature in many contexts, for reviews see, for example, http://dx.doi.org/10.3390/ijms20092167 and https://doi.org/10.1111/bph.13943. Alternatively, we could predict changes in bacterial membranes upon changing lipid composition (https://doi.org/10.1016/j.celrep.2020.108165).

For these predictions, we already have data in the databank for most relevant lipids except sphingomyelin and cardiolipin. Also, data for PI lipids is very few. Therefore, having any simulations with these lipids is very high priority now. Although all data is relevant now, especially if you or your colleague have any simulations with these lipids, it would be highly useful if you could upload this data to Zenodo and to the databank. Another underrepresented lipid class currently in the databank are polyunsaturated lipids. Also, for example ceramides would be good to have.

**Comment by ffavelar** [comment]
Data for POPC/PSM/Chol with Slipids (2013 version): https://zenodo.org/record/8307369

**Comment by suman-samantray** [comment]
I have 3 sets of simulation data for bilayer composed of POPC, POPE, POPS, CHOL, PSM, and GM1 lipids with "no counter-ions", NaCl ions, and CaCl2 ions (separate systems) for 300 ns each using Charmm36m FF

**Comment by jjmadsen** [comment]
@ohsOllila  In regards to your point 1), I have a simulation of a Gram-positive model membrane composition. It was aimed roughly at describing the S. aureus composition PG:lysyl-PG:CL (60:35:5). I will try to locate this trajectory and upload to it to Zenodo.

**Comment by jjmadsen** [comment]
Sorry for the delay. Here are the files: https://zenodo.org/record/8415046

**Comment by ohsOllila** [comment]
Thank you for your contributions. Based on these and other contributions, we have now made a machine learning model with @hsantila that predicts membrane properties from their composition. This is now added in the revised version of the manuscript, see
https://github.com/NMRLipids/DataBankManuscriptText/blob/main/main.pdf
https://github.com/NMRLipids/DataBankManuscriptText/blob/main/SI.pdf
https://github.com/NMRLipids/DataBankManuscript/blob/main/scripts/APLpredictor.ipynb
