### ISSUE TITLE
Merging createIDs.py to AddData.py

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/Databank#149]
Currently, https://github.com/NMRLipids/Databank/blob/main/Scripts/BuildDatabank/AddData.py creates README.yaml file from info.yaml file, and then the ID number is given by the separate code https://github.com/NMRLipids/Databank/blob/main/Scripts/BuildDatabank/createIDs.py.

It would make sense to merge the ID number generation into the AddData.py

**Comment by comcon1** [comment]
You can assign that issue to me. I'm able to merge them.

**Comment by comcon1** [comment]
We have discussed about it with @fsuarezleston and he said that `createID.py` should not be run after AddFile (as it is described in the documentation right now) and can be instead just run in the very end before synchronizing to the WebInterface. Shall we just remove createID.py from our protocol and move to some processing scripts? We can run it as CI-script before merge-request, for example.

**Comment by ohsOllila** [comment]
We have had some discussions with @comcon1, @fsuarezleston and @markussmiettinen outside this issue about proper generation of IDs. Maybe we should keep here roughly track on what are the current status and plans.

**Comment by comcon1** [comment]
We are testing now new solution, which can be described by 3 points:
- ID is created by CI/CD. 
- A contributor should not touch ID by himself. 
- ID for removed systems will become unavailable.
