### ISSUE TITLE
Moving order parameter calculation to AnalyzeDatabank from the AddData.py

### ISSUE THREAD

**Issue by batukav** [NMRLipids/Databank#15]
I am opening this issue mostly for the future reference. 

Currently AddData.py only analyzes the order parameters. We could think about removing the order parameter part from this script.

**Comment by ohsOllila** [comment]
Order parameter code is now part of QualityEvaluation.py.

**Comment by ohsOllila** [comment]
Order parameters are now calculated with a separate code: https://github.com/NMRLipids/Databank/blob/main/Scripts/AnalyzeDatabank/calcOrderParameters.py
I will close this.
