### ISSUE TITLE
data_to_json.py does not save error to JSON file

### ISSUE THREAD

**Issue by comcon1** [NMRLipids/Databank#165]
Subj. 

Errors are allowed to be provided in the DAT-file of the OrderParameter experiment folder, but then the DAT file should be converted according to the description of how to add an experiment, and errors don't come into JSON. As I understand, that behaviour is incorrect. 

Can I fix that and rebuild all  JSON files, which don't contain errors?

**Comment by ohsOllila** [comment]
I am not sure what do you mean with errors? Do you mean the comments in the beginning of the dat files? And you want to store those also to the json files? If this is the idea, how would you implement this in practice, i.e., how the comments would be stored in the json?

**Comment by comcon1** [comment]
I am coming back to this problem because I'm now adding more experimental datapoints. With "error" I meant errorbars. Experimental uncertainty. There could be quite different uncertainty regarding OP values and also there is always quite high uncertainty of hydration value. Both them should be stored and processed if you agree. 

If that is a part of `.dat` file:
```
M_G3_M M_G3H1_M          -0.21  0.01
M_G3_M M_G3H2_M          -0.21  0.01
M_G2_M M_G2H1_M          -0.19  0.01
M_G1_M M_G1H1_M          -0.14  0.02
M_G1_M M_G1H2_M           0.00  0.02
```
then I would do first that both numbers will store in JSON. That would close this ticket. 

Then I would like to open another ticket for processing these error values correctly somewhere. During number plotting, during FF quality estimation etc.

**Comment by ohsOllila** [comment]
Ok, I understand now. Yes, errors should be also stored in json files. It would be good if you could fix this. Discussion about handling the errors could be continued here, or then in another topic, whatever is easier for you.
