### ISSUE TITLE
High PCA equilibration times

### ISSUE THREAD

**Issue by PEFrankel** [NMRLipids/Databank#175]
Hi everyone,

I've been simulating bilayers using OpenFF parameters and have found trouble equilibrating my systems below the expected correlation time of <1 ns.

I am wondering if the PCA analysis could be describing whether the equilibrium motions are too slow, or whether it is just the approach to equilibrium that is being detected? I plan on printing the eigenvectors and clustering the configurations using MD Analysis, but I am not sure these will clarify where/how my systems are not equilibrating.

Control sims using the same equilibration methods, but with a different force field, did not have this issue. This could indicate it's an OpenFF issue, but I read a few of the previous issue tickets and I am not currently aware of a relevant, forcefield-specific issue (like polarizability) that could impact this.
Here are two simulations example simulations + the MDPs: 

- [This simulation](https://github.com/PEFrankel/OpenFF_Bilayer/tree/main/NMRlipid_Analysis/Databank/Data/Simulations/12e/f44/12ef44bcb769e27c4f02723a50ebc63d36384cdc/bfba408e40c03962a1fed0167c46ef4252ad6890) was equilibrated for 100 ns (40 NVT and 60 NPT) and has an EQ time of 13.2 ns.
- [This simulation](https://github.com/PEFrankel/OpenFF_Bilayer/tree/main/NMRlipid_Analysis/Databank/Data/Simulations/6a4/3f7/6a43f73bbc999443cfcaed5c916458dd44d6af79/0917efeb49c98c66f6d9084d17c3ab481ffb65ed) was equilibrated for 200 ns (80 NVT and 120 NPT) using the same parameters and it has a _longer_ EQ time of 22.1 ns.
- [MDPs used](https://github.com/PEFrankel/OpenFF_Bilayer/tree/main/New_Procedure/new_MDP)

**Comment by pbuslaev** [comment]
PCA equilibration time shows the time required for an individual lipid to equilibrate divided by trajectory length. So the value is unitless. The code is based on this [paper](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.5b01106). So it does not really matter how you equilibrate your trajectory, if in the production run lipids behave strangely, the equilibration time should be high. What you can do, is perform full PCA analysis (for example using this [code](https://github.com/membrane-systems/PCAlipids) and [tutorial](https://github.com/membrane-systems/PCAlipids/blob/master/tutorial/tutorial.md)) and share results here. What I  expect, is that conformations are strange. So maybe you can align lipid frames to each other and prepare and share a figure like this to begin with (this again can be easily done with [PCAlipids](https://github.com/membrane-systems/PCAlipids)):

![image](https://github.com/NMRLipids/Databank/assets/10205508/afa56614-a19b-48e2-9744-f3d872650e41)

**Comment by PEFrankel** [comment]
Thank you for the guidance! The tutorial is quite useful, although, I did run into an issue where hydrogens were being included in the average structure when uploading a GRO file (for OpenFF only - I tested others). I may look into this, but for the time being, I attached the PCA results. The conformation and principal component images are the most notable and I can't explain them in terms of the force field parameters quite yet. The paper does state lower-amplitude components to be affected more by the force field, but these results are significant already, so I didn't bother. I'm confident now, but let me know your thoughts and if you agree that this is a force field issue.

The paper also states PCA could be a method of phase analysis. APL, isomerization, and MSD tests all indicate this bilayer to be in the gel phase, but I am wondering if you know a more consistent test of bilayer phase? 

[OpenFF_POPC_PCA.zip](https://github.com/NMRLipids/Databank/files/14734095/OpenFF_POPC_PCA.zip)
- Note that the "control" used in the eigenvalue plot is the tutorial trajectory.

**Comment by pbuslaev** [comment]
Hm, it seems that somehow there are jumps over the box boundary. At least this can explain the strange conformations you are getting and those strange conformations in turn can lead to slow dynamics. I need to check the trajectory and atom naming to understand what could have caused this behaviour.

**Comment by ohsOllila** [comment]
From my (very quick) visual inspection of OpenFF trajectories with vmd gave me an impression that the lipids are moving much less than in other simulations. It might be useful to confirm this by visually comparing OpenFF and other trajectories.

**Comment by davidlmobley** [comment]
This is just a note that, at OpenFF, we will hopefully begin to look in these directions in the coming months (and are seeking funding to accelerate work in this direction). However, internally we've devoted no attention to lipids at all. We are very keen to receive suggestions about appropriate benchmarks, etc. So please feel free to share experiences with us!

**Comment by ohsOllila** [comment]
Great to hear that you are accelerating lipid work in OpenFF!

Question on benchmarks is highly relevant and I have opened another issue on that: https://github.com/NMRLipids/Databank/issues/186
