### ISSUE TITLE
Problem in adding data

### ISSUE THREAD

**Issue by ohsOllila** [NMRLipids/Databank#177]
Hello! 
I wanted to resurface this issue because I am running into a problem where the AddData script stops, asks me if I still want to proceed even though the number of atoms in my trajectory and README.yaml do not match. My mapping files seem to be labeled correctly, however there is overlap between the atom naming of my lipid and solvent mapping files (not sure if that is the problem).

Possibly because of this issue, I am able to run certain analysis scripts (apl, eqtimes, OP), but not others (Form Factor, bilayer thickenss). Any insight on these issues would be very helpful, thanks!

_Originally posted by @JHoeflich1 in https://github.com/NMRLipids/Databank/issues/150#issuecomment-2030193735_

**Comment by ohsOllila** [comment]
I moved this to its own issue from here https://github.com/NMRLipids/Databank/issues/150 because this is a specific case rather than general development of sanity checks.

Would it be possible to share the info file for which you have the problem?

I also noticed only now the pull requests that you made already some time ago. After some small changes, I was able to successfully add and analyze info file from this pull request https://github.com/NMRLipids/Databank/pull/174 (the results are here: https://github.com/NMRLipids/Databank/tree/main/Data/Simulations/4f5/fb4/4f5fb4c911390b50b56d06364c85910c10191c57/ea16a8b51b9d71838d911eb3cebbc69ad05600d8). However, the other one seems to have a problem that the doi link cannot be found: https://github.com/NMRLipids/Databank/pull/173 (this is now moved to this folder https://github.com/NMRLipids/Databank/tree/main/Scripts/BuildDatabank/info_files/793 because there was already something else in the original folder).

**Comment by JHoeflich1** [comment]
Thank you. The issue I was having was with analyzing the pull request (#174) mentioned above, but seeing that you successfully analyzed the system makes me wonder what I was doing wrong. Could you elaborate on the changes you made to add and analyze the info file? That may be the source of my problem

**Comment by ohsOllila** [comment]
Main changes are here: https://github.com/NMRLipids/Databank/commit/529a554e7761ab4097da18c42d4ac42e220e0ac4#diff-04f37820ade9287806fc6f85902bd9711425e11858bde136ba13d59e4269ca1d

Equilibration time was fixed, molecule naming convention was fixed, and there was a typo in mapping file.

I will close this issue now.
